# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jNIOG8EGcWE5rShz69aja2Dl17kMP4Qo
"""

print("Welcome to my computer quiz!")

playing = input("Do you want to play? ")
score = 0
if playing.lower() != "yes":
    quit()
else:
    print("Okay! Let's play :)")
    

    answer = input("What does CPU stand for? ")
    if answer.lower() == "central processing unit":
        print('Correct!')
        score += 1
    else:
        print("Incorrect!")

    answer = input("What does GPU stand for? ")
    if answer.lower() == "graphics processing unit":
        print('Correct!')
        score += 1
    else:
        print("Incorrect!")

    answer = input("What does RAM stand for? ")
    if answer.lower() == "random access memory":
        print('Correct!')
        score += 1
    else:
        print("Incorrect!")

    answer = input("What does PSU stand for? ")
    if answer.lower() == "power supply":
      print('Correct!')
      score += 1
    else:
      print("Incorrect!")

print("You got " + str(score) + " questions correct!")
print("You got " + str((score / 4) * 100) + "%.")